import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Podcast from '../dashboard/PodcatsLinks'
import People from '../dashboard/PeopleLinks'
import Music from '../dashboard/MusicLink'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='p-6'>
        <h1 className='truncate text-2xl font-bold'>Linkpears 🍐 </h1>
        <span className='truncate'> Thomas Cavalcante</span>
      </div>
      <p className='text-center italic'>Stuff I like. On the internet.</p>
      <main className={styles.main}>
        <div className='mb-20'>
          <People/>
          <Music/>
          <Podcast/>
        </div>
      </main>
    </>
  )
}
